modLoader="javafml"
loaderVersion="[3,)"
license="MIT"

[[mods]]
modId="ore_yield"
version="${file.jarVersion}"
displayName="Ore Yield"
authors="WinWeirdo"
logoFile="icon.png"
description='''Ores are earned from breaking stone-like blocks instead of generating as ore blocks.'''

[[dependencies.ore_yield]]
modId="neoforge"
mandatory=true
versionRange="{{loader_range}}"
ordering="NONE"
side="BOTH"

[[dependencies.ore_yield]]
modId="minecraft"
mandatory=true
versionRange="{{minecraft_range}}"
ordering="NONE"
side="BOTH"
