plugins {
    id 'java'
    id 'dev.architectury.loom'
    id 'com.gradleup.shadow'
}

base { archivesName = 'ore-yield-fabric' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

loom {
    silentMojangMappingsLicense()
}

repositories {
    maven { url = 'https://maven.terraformersmc.com/releases/' }
}

configurations {
    common
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    modCompileOnly "com.terraformersmc:modmenu:${mod_menu_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.common]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
