plugins {
    id 'dev.architectury.loom' version "${loom_version}" apply false
    id 'net.minecraftforge.gradle' version "${forgegradle_version}" apply false
    id 'com.gradleup.shadow' version "${shadow_version}" apply false
}

subprojects {
    group = 'com.oreyield'
    version = rootProject.findProperty('mod_version') ?: '1.0.3'
}
