modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="ore_yield"
version="${file.jarVersion}"
displayName="Ore Yield"
authors="Ore Yield"
description='''Ores are earned from breaking stone-like blocks instead of generating as ore blocks.'''

[[dependencies.ore_yield]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.ore_yield]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
