buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'java'
    id 'net.minecraftforge.gradle'
}

apply plugin: 'org.spongepowered.mixin'

base { archivesName = 'ore-yield-forge' }

java.toolchain.languageVersion = JavaLanguageVersion.of({{java}})

minecraft {
    mappings channel: 'official', version: '{{mc}}'
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                ore_yield {
                    source sourceSets.main
                    source project('{{common_project}}').sourceSets.main
                }
            }
        }
        client {}
        server { args '--nogui' }
        data {
            workingDirectory project.file('run-data')
            args '--mod', 'ore_yield', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

configurations {
    common
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude 'ore-yield/generated_ores.json'
}

dependencies {
    minecraft "net.minecraftforge:forge:{{forge}}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    common(project(path: '{{common_project}}', configuration: 'namedElements')) { transitive = false }
    implementation(project(path: '{{common_project}}', configuration: 'namedElements')) { transitive = false }
}

mixin {
    add sourceSets.main, 'ore_yield.forge.refmap.json'
    config 'ore_yield.forge.mixins.json'
}

tasks.named('jar', Jar).configure {
    from(configurations.common.collect { it.isDirectory() ? it : zipTree(it) })
    manifest {
        attributes([
                'Specification-Title': 'ore-yield',
                'Specification-Vendor': 'oreyield',
                'Implementation-Title': project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'MixinConfigs': 'ore_yield.forge.mixins.json'
        ])
    }
}
