plugins {
    id 'java-library'
    id 'dev.architectury.loom'
}

base { archivesName = 'ore-yield-common' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

loom {
    silentMojangMappingsLicense()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
}
